PRINT '[Preflight] Starting...';
GO
ALTER DATABASE CURRENT SET MAXDOP = 1 WITH NO_WAIT;
GO
ALTER DATABASE CURRENT SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
GO
PRINT '[Preflight] MAXDOP=1, Async Stats=ON.';
GO
